import type { ForestConfig } from '../../types';

export const forestDefaults: ForestConfig = {
  defaultVariant: 'none',
  placement: {
    seed: 20260910,
    jitterRatio: 0.42,
    corridorCoreHalfWidthMeters: 420,
    corridorFeatherMeters: 380,
    routeClearanceMeters: 16,
    slopeFalloffStartDeg: 38,
    slopeZeroDeg: 58,
    distanceFieldCellMeters: 16,
    maxRouteDistanceMeters: 800,
  },
  tree: {
    budget: { spacingMeters: 15, maxInstances: 13300 },
    minHeightMeters: 16,
    maxHeightMeters: 26,
    crownRadiusRatio: 0.22,
    crownBaseRatio: 0.30,
    crownRadialSegments: 6,
    crownHeightSegments: 2,
    trunkRadiusRatio: 0.018,
    crownColor: 0x4e6b3f,
    trunkColor: 0x554233,
    crownBottomShade: 0.55,
    colorJitterStrength: 0.22,
  },
  billboard: {
    budget: { spacingMeters: 7.5, maxInstances: 64000 },
    minHeightMeters: 16,
    maxHeightMeters: 26,
    aspectRatio: 0.62,
    crossQuadCount: 2,
    topCardEnabled: true,
    topCardHeightRatio: 0.78,
    topCardSizeRatio: 0.72,
    textureSize: 128,
    textureSeed: 20260911,
    alphaTest: 0.34,
    tintColor: 0xffffff,
    colorJitterStrength: 0.18,
  },
  canopy: {
    budget: { spacingMeters: 16, maxInstances: 18000 },
    minRadiusMeters: 11,
    maxRadiusMeters: 19,
    heightRatio: 0.62,
    sinkRatio: 0.34,
    lumpiness: 0.22,
    subdivision: 0,
    color: 0x50693e,
    bottomShade: 0.45,
    colorJitterStrength: 0.24,
  },
};
